### ISSUE TITLE
Convert to PWA

### ISSUE THREAD

**Issue by maseiler** [maseiler/avh-booking-system#120]
Convert to progressive web app (PWA) to hide browser controls (and optionally enable mobile versions)

**Comment by ebert-l** [comment]
pwa should focus on the installable pwa itself. The responsive Design can be handled in another issue.

The branch v2-pwa holds a first, functional setup for the avhbs v1 as a pwa.
The Icons and Colors of the Navbar are off because i used test colors and test images. But the functionality can be tested.

Please run a `npm install` after branch checkout to download all new neccessary packets (vue-pwa).

**Comment by ebert-l** [comment]
Oh, and note, that your Browser will not offer the installation of the pwa if the connection is not a trusted ssl connection.
HTTPS is a must from now, even in development.
